import Foundation

/// Stable cross-client capability identifiers. The JSON-compatible YAML contract is the
/// source of truth; this enum makes accidental native capability removal a compile-time
/// and CI-visible change.
enum ClientCapabilityID: String, CaseIterable, Codable, Hashable, Sendable {
    case bootstrapClientCompatibility = "bootstrap.client-compatibility"
    case authMobileLogin = "auth.mobile-login"
    case authMobileRefresh = "auth.mobile-refresh"
    case authMobileSession = "auth.mobile-session"
    case authMobileLogout = "auth.mobile-logout"
    case authMobileDevices = "auth.mobile-devices"
    case authMobileDeviceRevoke = "auth.mobile-device-revoke"
    case homeReadiness = "home.readiness"
    case homeSystemHealth = "home.system-health"
    case eventsCatchUp = "events.catch-up"
    case eventsStream = "events.stream"
    case ideaPreview = "idea.preview"
    case ideaStartResearch = "idea.start-research"
    case researchProgramList = "research.program-list"
    case researchProgramDetail = "research.program-detail"
    case researchMissions = "research.missions"
    case researchActivity = "research.activity"
    case researchPause = "research.pause"
    case researchResume = "research.resume"
    case researchArchive = "research.archive"
    case researchRestore = "research.restore"
    case alphaLibrary = "alpha.library"
    case alphaDetail = "alpha.detail"
    case portfolioMandates = "portfolio.mandates"
    case portfolioPrograms = "portfolio.programs"
    case portfolioCandidateDetail = "portfolio.candidate-detail"
    case approvalInbox = "approval.inbox"
    case approvalApprove = "approval.approve"
    case approvalReject = "approval.reject"
    case handoffRegistry = "handoff.registry"
    case handoffRevoke = "handoff.revoke"
    case adminRuntimeRead = "admin.runtime-read"
    case adminRuntimeUpdate = "admin.runtime-update"
    case adminMandateEnable = "admin.mandate-enable"
    case adminMandateDisable = "admin.mandate-disable"
    case adminDataSources = "admin.data-sources"
    case adminDataSourceRegister = "admin.data-source-register"
    case adminDatasets = "admin.datasets"
    case adminUniverses = "admin.universes"
    case adminDownstreams = "admin.downstreams"
    case adminDownstreamRegister = "admin.downstream-register"
    case adminPluginReleases = "admin.plugin-releases"
}
