//! Runtime-owned immutable native catalog metadata, never client assertions of evidence.
use crate::{
    research::{DataOrigin, DataPartition, PitStatus},
    runtime::RuntimeDataKind,
    DbCounter, SchemaV1,
};
use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use utoipa::ToSchema;

#[derive(Clone, Copy, Debug, Eq, PartialEq, Serialize, Deserialize, ToSchema)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum DataRevisionPolicy {
    AsKnownThen,
    Restated,
    Unknown,
}

#[derive(Clone, Debug, Serialize, Deserialize, ToSchema)]
#[serde(deny_unknown_fields)]
pub struct NativeUniverseMemberV1 {
    #[schema(min_length = 1, max_length = 200)]
    pub instrument_id: String,
    pub valid_from: DateTime<Utc>,
    pub valid_until: Option<DateTime<Utc>>,
    pub available_at: DateTime<Utc>,
    /// None means unknown classification; Some([]) is explicitly ungrouped.
    #[schema(max_items = 64)]
    pub groups: Option<Vec<String>>,
}

#[derive(Clone, Debug, Serialize, Deserialize, ToSchema)]
#[serde(deny_unknown_fields)]
pub struct NativeUniverseV1 {
    #[schema(min_length = 1, max_length = 120)]
    pub name: String,
    #[schema(min_length = 1, max_length = 120)]
    pub calendar_ref: String,
    #[schema(min_length = 1, max_length = 120)]
    pub calendar_version: String,
    pub calendar_sessions: Option<crate::science::NativeCalendarSessionsV1>,
    pub selection_asof: DateTime<Utc>,
    pub has_historical_membership: bool,
    pub coverage_start: DateTime<Utc>,
    pub coverage_end: DateTime<Utc>,
    #[schema(min_items = 1, max_items = 4096)]
    pub membership: Vec<NativeUniverseMemberV1>,
    /// Original Rust InstrumentAny externally tagged Serde definitions, e.g. {"CurrencyPair":{...}}.
    /// This document is metadata, not a second instrument or matching engine.
    #[schema(min_items = 1, max_items = 256)]
    pub instrument_definitions: Vec<serde_json::Value>,
}

#[derive(Clone, Debug, Serialize, Deserialize, ToSchema)]
#[serde(deny_unknown_fields)]
pub struct RuntimeCatalogMetadataV1 {
    pub schema_version: SchemaV1,
    #[schema(min_length = 1, max_length = 512)]
    pub registered_ref: String,
    #[schema(min_length = 1, max_length = 512)]
    pub native_snapshot_ref: String,
    #[schema(min_length = 1, max_length = 120)]
    pub storage_version: String,
    #[schema(min_length = 1, max_length = 120)]
    pub provider_kind: String,
    pub data_kind: RuntimeDataKind,
    pub partition: DataPartition,
    pub event_start: DateTime<Utc>,
    pub event_end: DateTime<Utc>,
    pub available_through: DateTime<Utc>,
    pub row_count: DbCounter,
    pub origin: DataOrigin,
    pub pit_status: PitStatus,
    pub revision_policy: DataRevisionPolicy,
    #[schema(min_length = 1, max_length = 2000)]
    pub provenance_reference: String,
    /// A recorded source explanation. Never inferred merely from ts_init <= cutoff.
    #[schema(min_length = 1, max_length = 8000)]
    pub availability_provenance: String,
    pub universe: NativeUniverseV1,
    /// Exact original quality report generated by the native source owner.
    /// Fresh DATA_VALIDATE still reopens the registered snapshot before consumption.
    pub quality: crate::execution::NativeDataQualityReportV1,
    /// Original source attachment descriptors. The registered Dataset and native
    /// metadata artifact preserve the source association without extending license scope.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub recorded_feature_inputs: Option<RecordedFeatureInputsV1>,
}

#[derive(Clone, Debug, Deserialize, ToSchema)]
#[serde(deny_unknown_fields)]
pub struct CatalogVersionQuery {
    #[schema(min_length = 1, max_length = 120)]
    pub storage_version: String,
}

#[derive(Clone, Debug, Eq, PartialEq, Serialize, Deserialize, ToSchema)]
#[serde(deny_unknown_fields)]
pub struct RecordedFeatureFragmentV1 {
    /// Stable attachment key, never a filesystem path.
    #[schema(
        min_length = 1,
        max_length = 120,
        pattern = r"^[A-Za-z0-9][A-Za-z0-9._-]{0,119}(?![\s\S])"
    )]
    pub part_key: String,
    #[schema(schema_with = recorded_feature_bytes_schema)]
    pub byte_count: DbCounter,
    #[schema(schema_with = recorded_feature_observations_schema)]
    pub observations: DbCounter,
    pub min_event_ns: DbCounter,
    pub max_event_ns: DbCounter,
    pub min_observed_available_ns: DbCounter,
    pub max_observed_available_ns: DbCounter,
}

#[derive(Clone, Debug, Eq, PartialEq, Serialize, Deserialize, ToSchema)]
#[serde(deny_unknown_fields)]
pub struct RecordedFeatureInputsV1 {
    pub schema_version: SchemaV1,
    /// Original source event selection [start, end), independent of BAR closes.
    pub source_selection_start_ns: DbCounter,
    pub source_selection_end_ns: DbCounter,
    pub partition: DataPartition,
    /// At most 100000 observations in total; each part retains original bytes.
    #[schema(min_items = 1, max_items = 16)]
    pub fragments: Vec<RecordedFeatureFragmentV1>,
}

pub(crate) fn recorded_feature_bytes_schema(
) -> utoipa::openapi::RefOr<utoipa::openapi::schema::Schema> {
    crate::scalars::bounded_bigint_schema(crate::artifacts::MAX_UPLOAD_BYTES as u64, true)
}

fn recorded_feature_observations_schema() -> utoipa::openapi::RefOr<utoipa::openapi::schema::Schema>
{
    crate::scalars::bounded_bigint_schema(crate::science::MAX_FEATURE_OBSERVATIONS as u64, true)
}
