//! Runtime-owned immutable native catalog metadata, never client assertions of evidence.
use crate::{
    research::{DataOrigin, DataPartition, PitStatus},
    runtime::RuntimeDataKind,
    DbCounter, SchemaV1,
};
use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use utoipa::ToSchema;

#[derive(Clone, Copy, Debug, Eq, PartialEq, Serialize, Deserialize, ToSchema)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum DataRevisionPolicy {
    AsKnownThen,
    Restated,
    Unknown,
}

#[derive(Clone, Debug, Serialize, Deserialize, ToSchema)]
#[serde(deny_unknown_fields)]
pub struct NativeUniverseMemberV1 {
    #[schema(min_length = 1, max_length = 200)]
    pub instrument_id: String,
    pub valid_from: DateTime<Utc>,
    pub valid_until: Option<DateTime<Utc>>,
    pub available_at: DateTime<Utc>,
}

#[derive(Clone, Debug, Serialize, Deserialize, ToSchema)]
#[serde(deny_unknown_fields)]
pub struct NativeUniverseV1 {
    #[schema(min_length = 1, max_length = 120)]
    pub name: String,
    #[schema(min_length = 1, max_length = 120)]
    pub calendar_ref: String,
    #[schema(min_length = 1, max_length = 120)]
    pub calendar_version: String,
    pub selection_asof: DateTime<Utc>,
    pub has_historical_membership: bool,
    pub coverage_start: DateTime<Utc>,
    pub coverage_end: DateTime<Utc>,
    #[schema(min_items = 1, max_items = 4096)]
    pub membership: Vec<NativeUniverseMemberV1>,
    /// Original native serialized definitions, checked by the native catalog job.
    /// This document is metadata, not a second instrument or matching engine.
    #[schema(min_items = 1, max_items = 256)]
    pub instrument_definitions: Vec<serde_json::Value>,
}

#[derive(Clone, Debug, Serialize, Deserialize, ToSchema)]
#[serde(deny_unknown_fields)]
pub struct RuntimeCatalogMetadataV1 {
    pub schema_version: SchemaV1,
    #[schema(min_length = 1, max_length = 512)]
    pub registered_ref: String,
    #[schema(min_length = 1, max_length = 512)]
    pub native_snapshot_ref: String,
    #[schema(min_length = 1, max_length = 120)]
    pub storage_version: String,
    #[schema(min_length = 1, max_length = 120)]
    pub provider_kind: String,
    pub data_kind: RuntimeDataKind,
    pub partition: DataPartition,
    pub event_start: DateTime<Utc>,
    pub event_end: DateTime<Utc>,
    pub available_through: DateTime<Utc>,
    pub row_count: DbCounter,
    pub origin: DataOrigin,
    pub pit_status: PitStatus,
    pub revision_policy: DataRevisionPolicy,
    #[schema(min_length = 1, max_length = 2000)]
    pub provenance_reference: String,
    /// A recorded source explanation. Never inferred merely from ts_init <= cutoff.
    #[schema(min_length = 1, max_length = 8000)]
    pub availability_provenance: String,
    pub universe: NativeUniverseV1,
    /// Exact original quality report generated by the native source owner.
    /// Fresh DATA_VALIDATE still reopens the registered snapshot before consumption.
    pub quality: crate::execution::NativeDataQualityReportV1,
}

#[derive(Clone, Debug, Deserialize, ToSchema)]
#[serde(deny_unknown_fields)]
pub struct CatalogVersionQuery {
    #[schema(min_length = 1, max_length = 120)]
    pub storage_version: String,
}
