//! Strict wire types shared by the control-plane entrypoints.
//!
//! This initial slice does not implement HTTP routes, persistence, authorization,
//! independent evaluation, or the complete Issue 62 acceptance contract.
#![forbid(unsafe_code)]

pub mod artifacts;
pub mod auth;
pub mod brief;
pub mod budget;
pub mod codex;
pub mod control;
pub mod cycles;
pub mod evidence;
pub mod experiments;
pub mod lifecycle;
pub mod portfolio;
pub mod research;
pub mod runs;
pub mod runtime;
pub mod runtime_jobs;
pub mod scalars;
pub mod science;
pub mod settings;

pub use scalars::{DbCounter, DecimalValue, Id, Revision, SchemaV1, Timestamp};

use utoipa::OpenApi;

#[derive(OpenApi)]
#[openapi(components(schemas(
    cycles::BriefFreezeV1,
    cycles::FrozenBriefV1,
    cycles::CycleStartIntent,
    cycles::CycleViewV1,
    cycles::CycleStartedV1,
    runtime::RuntimeCapabilitiesV1,
    runtime_jobs::JobSpecV1,
    runtime_jobs::RuntimeJobStatusV1,
    runtime_jobs::RuntimeCancelV1,
    runtime_jobs::ResultManifestV1,
    runtime_jobs::RuntimeObjectReceiptV1,
    runtime::RuntimeProbeRequestV1,
    runtime::RuntimeProbeViewV1,
    runtime::RuntimeReadinessV1,
    settings::IntegrationSecretCreate,
    settings::IntegrationSecretView,
    settings::RuntimeCreate,
    settings::RuntimeUpdate,
    settings::RuntimeView,
    settings::DownstreamCreate,
    settings::DownstreamUpdate,
    settings::DownstreamView,
    artifacts::ArtifactCreate,
    artifacts::ArtifactView,
    brief::BriefCreate,
    brief::BriefCreateIntent,
    brief::BriefUpdate,
    brief::BriefView,
    research::InputSetCreate,
    research::InputSetView,
    research::InputSetSummary,
    research::ResearchListQuery,
    research::EvaluationPolicyCreate,
    research::EvaluationPolicyView,
    research::FieldIssue,
    control::MachineSessionView,
    control::ProjectCreate,
    control::ProjectUpdate,
    control::ProjectView,
    control::ListQuery,
    control::PrincipalCreate,
    control::PrincipalUpdate,
    control::PrincipalView,
    control::CredentialIssue,
    control::CredentialRevoke,
    control::CredentialView,
    control::CredentialCreated,
    control::OperatorCommand,
    control::OperatorGrantRequest,
    control::OperatorGrantView,
    auth::BootstrapStart,
    auth::BootstrapEnrollment,
    auth::BootstrapConfirm,
    auth::LoginRequest,
    auth::VerifyRequest,
    auth::BootstrapStatus,
    auth::BrowserSession,
    auth::TrustedDevice,
    auth::DeviceList,
    SchemaV1,
    Id,
    DbCounter,
    Revision,
    DecimalValue,
    budget::BudgetV1,
    budget::CostEnforcement,
    budget::StopRuleV1,
    codex::ConnectionMode,
    codex::ProfileOrigin,
    codex::SavedModelSettingsV1,
    codex::ModelCapabilityV1,
    codex::ReasoningEffortCapability,
    evidence::MetricStatus,
    evidence::EvidenceStatus,
    evidence::Decision,
    evidence::Comparator,
    evidence::MetricRequirementV1,
    evidence::MetricValueV1,
    experiments::ExperimentProposalV1,
    experiments::ExperimentView,
    runs::ProjectState,
    runs::RunState,
    runs::RunKind,
    runs::RunSnapshotV1,
    lifecycle::JobLimitsV1,
    lifecycle::RunCancelV1,
    lifecycle::RunListQuery,
    lifecycle::RunEventKind,
    lifecycle::RunStatePayload,
    lifecycle::RunEventV1,
    lifecycle::RunEventBatchV1,
    portfolio::AllocationInputV1,
    portfolio::AllocationResultV1,
    science::NativeForecastRequestV1,
    science::NativeForecastResultV1,
    science::NativeSimulationRequestV1,
    science::NativeSimulationResultV1
)))]
struct DomainContracts;

/// Deterministic, native-generator output. No handwritten parallel JSON schema.
pub fn openapi_json() -> Result<String, serde_json::Error> {
    let mut document = DomainContracts::openapi();
    document.info.title = "QuaZonai typed domain contracts (initial slice)".into();
    document.info.description = Some(
        "Shared strict domain and authentication DTOs. \
         HTTP routes are generated by the server crate; no full-system acceptance is implied."
            .into(),
    );
    let mut value = serde_json::to_value(document)?;
    value.sort_all_objects();
    Ok(serde_json::to_string_pretty(&value)? + "\n")
}
