import { expect, test } from '@playwright/test';
import { readFile } from 'node:fs/promises';
import { navigate, settingsCategory } from './fixtures';

test.use({ baseURL: 'http://127.0.0.1:4179' });

test('synthetic preview renders native-contract records without a backend or writable delivery', async ({ page }) => {
  test.setTimeout(60_000);
  const failures: string[] = [];
  const eventRequests: string[] = [];
  page.on('pageerror', error => failures.push(error.message));
  page.on('response', response => {
    const path = new URL(response.url()).pathname;
    if (path.startsWith('/api/') && response.request().method() === 'GET' && !response.ok()) failures.push(`${response.status()} ${path}`);
  });
  page.on('request', request => { if (new URL(request.url()).pathname.endsWith('/events')) eventRequests.push(request.url()); });
  await page.goto('/');
  const notice = page.getByRole('note', { name: '合成预览说明' });
  await expect(notice).toContainText('SYNTHETIC / FIXTURE');
  await expect(notice).toContainText('项目状态（启用需冻结 Brief，归档不可退出）');
  await expect(notice).toContainText('新 Cycle 不执行实验、不生成合格候选');
  await expect(notice).toContainText('没有真实账号、科学计算、资格、审批或下游交付');
  await expect(page.getByRole('button', { name: 'SYNTHETIC · 双 Alpha 研究示例', exact: true })).toBeVisible()
    .catch(error => { throw new Error(`${error.message}\nBrowser errors: ${failures.join('; ')}`); });
  await page.getByRole('button', { name: 'SYNTHETIC · 双 Alpha 研究示例', exact: true }).click();
  await page.getByRole('button', { name: '查看冻结版本', exact: true }).click();
  const brief = page.getByRole('dialog', { name: 'Brief · 版本 1', exact: true });
  await expect(brief.getByText('只读版本', { exact: true })).toBeVisible();
  await page.keyboard.press('Escape');
  await expect(brief).toBeHidden();
  await page.getByRole('tab', { name: '研究周期', exact: true }).click();
  await expect(page.getByRole('cell', { name: /^NO_SUPPORTED_CANDIDATE / })).toBeVisible();
  await page.getByRole('button', { name: '查看试验选择', exact: true }).click();
  const selection = page.getByRole('dialog', { name: '冻结试验选择', exact: true });
  await expect(selection.getByText('选择完成不是科学 PASS、Sealed 或可交付资格。', { exact: true })).toHaveCount(0);
  await expect(selection.getByText('2 / 0 / 0 / 0', { exact: true })).toBeVisible();
  await expect(selection.getByText('INVALID_EVIDENCE', { exact: true })).toHaveCount(2);
  await page.keyboard.press('Escape');
  await expect(selection).toBeHidden();
  await navigate(page, 'Alpha');
  await page.getByRole('combobox', { name: '选择 Alpha 所属项目', exact: true }).click();
  await page.locator('.ant-select-dropdown:visible .ant-select-item-option-content').filter({ hasText: 'SYNTHETIC · 双 Alpha' }).click();
  for (const n of [1, 2]) await expect(page.getByRole('button', { name: `SYNTHETIC · 信号 ${n}`, exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'SYNTHETIC · 信号 1', exact: true }).click();
  await page.getByRole('button', { name: '版本 1', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Alpha 版本 1', exact: true })).toBeVisible();
  await expect(page.getByText('FIXTURE', { exact: true }).first()).toBeVisible();
  await navigate(page, '组合');
  await page.getByRole('combobox', { name: '选择组合所属项目', exact: true }).click();
  await page.locator('.ant-select-dropdown:visible .ant-select-item-option-content').filter({ hasText: 'SYNTHETIC · 双 Alpha' }).click();
  await page.getByRole('button', { name: '配置 v1', exact: true }).click();
  const mandate = page.getByRole('dialog', { name: '不可变组合配置', exact: true });
  await expect(mandate.getByText(/clarabel::solver::DefaultSolver/)).toBeVisible();
  await page.keyboard.press('Escape');
  await expect(mandate).toBeHidden();
  await page.getByRole('tab', { name: '候选快照', exact: true }).click();
  await page.getByRole('button', { name: '01990000-0000-7000-8000-000000000203', exact: true }).click();
  const candidate = page.getByRole('dialog', { name: '不可变候选快照', exact: true });
  await expect(candidate.getByText('SYNTHETIC_NO_QUALIFIED_ALPHA', { exact: true })).toBeVisible();
  await expect(candidate.getByText('暂无目标', { exact: true })).toBeVisible();
  await expect(candidate.getByRole('button', { name: '请求组合 Study', exact: true })).toBeDisabled();
  await page.keyboard.press('Escape');
  await expect(candidate).toBeHidden();
  await page.getByRole('tab', { name: '执行假设', exact: true }).click();
  await page.getByRole('button', { name: /^查看假设 / }).click();
  const assumptions = page.getByRole('dialog', { name: '不可变执行假设', exact: true });
  await expect(assumptions.getByText('CONSERVATIVE_ASSUMPTION · 保守假设，不是数据支持成本证明', { exact: true })).toBeVisible();
  await page.keyboard.press('Escape');
  await expect(assumptions).toBeHidden();
  await page.getByRole('tab', { name: '评估政策', exact: true }).click();
  await page.getByRole('button', { name: '政策 v1', exact: true }).click();
  const policy = page.getByRole('dialog', { name: '不可变评估政策', exact: true });
  await expect(policy.getByLabel('原完整评估政策', { exact: true })).toContainText('SYNTHETIC · 仅合成研究，不授予真实资格');
  await page.keyboard.press('Escape');
  await expect(policy).toBeHidden();
  await navigate(page, '交付');
  await page.getByRole('combobox', { name: '选择交付所属项目', exact: true }).click();
  await page.locator('.ant-select-dropdown:visible .ant-select-item-option-content').filter({ hasText: 'SYNTHETIC · 双 Alpha' }).click();
  await page.getByRole('button', { name: 'Release 00000510', exact: true }).click();
  const release = page.getByRole('dialog', { name: '原始目标包版本', exact: true });
  await expect(release.getByText('DEMO 目标包不能用于 Paper 或 Live 审批及交付。', { exact: true })).toBeVisible();
  await expect(release.getByRole('button', { name: '审批此目标包', exact: true })).toBeDisabled();
  const download = page.waitForEvent('download');
  await release.getByRole('button', { name: '下载原始目标包', exact: true }).click();
  const file = await download;
  const body = JSON.parse(await readFile((await file.path())!, 'utf8'));
  expect(body.environment_origin).toBe('DEMO');
  expect(body.release_id).toBe('01990000-0000-7000-8000-000000000510');
  expect(body.limitations.join(' ')).toContain('没有执行优化、评估或授予真实资格');
  await release.getByText('原审批历史', { exact: true }).click();
  await expect(release.getByText('原目标包尚无审批记录。', { exact: true })).toBeVisible();
  await page.keyboard.press('Escape');
  await expect(release).toBeHidden();
  await page.getByRole('tab', { name: '交付记录', exact: true }).click();
  await expect(page.getByText('暂无交付记录', { exact: true })).toBeVisible();
  await page.getByRole('tab', { name: '自动化政策', exact: true }).click();
  await expect(page.getByRole('button', { name: '冻结自动化政策', exact: true })).toBeVisible();
  await navigate(page, '运行');
  await page.getByRole('button', { name: 'PORTFOLIO_BUILD · 00000202', exact: true }).click();
  const run = page.getByRole('dialog', { name: '运行详情', exact: true });
  await expect(run.getByText('无自动再平衡关联', { exact: true })).toBeVisible();
  await expect(run.getByRole('button', { name: '请求取消运行', exact: true })).toBeDisabled();
  await expect(run.getByText(/运行已终止。/)).toBeVisible();
  expect(eventRequests).toEqual([]);
  await page.keyboard.press('Escape');
  await expect(run).toBeHidden();
  await navigate(page, '设置');
  await settingsCategory(page, '数据');
  await expect(page.getByText('SYNTHETIC · 演示目录', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: '查看许可与版本登记', exact: true }).click();
  await expect(page.getByText('SYNTHETIC · 未连接 Runtime', { exact: true })).toBeVisible();
  await expect(page.getByText('SYNTHETIC · 已过期的演示许可', { exact: true })).toBeVisible();
  await expect(page.getByRole('button', { name: '登记原生数据版本', exact: true })).toBeDisabled();
  await page.getByRole('tab', { name: '已登记数据版本', exact: true }).click();
  await expect(page.getByRole('button', { name: '查看版本证据', exact: true })).toHaveCount(3);
  await page.getByRole('combobox', { name: '筛选数据分区', exact: true }).click();
  await page.locator('.ant-select-dropdown:visible .ant-select-item-option-content').getByText('SEALED', { exact: true }).click();
  await expect(page.getByRole('button', { name: '查看版本证据', exact: true })).toHaveCount(1);
  await page.getByRole('button', { name: '查看版本证据', exact: true }).click();
  const dataset = page.getByRole('dialog', { name: '原生数据版本与证据', exact: true });
  await expect(dataset.getByText('测试数据 · PIT UNVERIFIED', { exact: true })).toBeVisible();
  await expect(dataset.getByText('SEALED', { exact: true })).toBeVisible();
  await dataset.getByRole('button', { name: '关闭', exact: true }).click();
  await expect(dataset).toBeHidden();
  await page.getByRole('tab', { name: 'Universe 版本', exact: true }).click();
  await expect(page.getByText('SYNTHETIC · 演示投资域', { exact: true })).toBeVisible();
  await expect(page.getByText('历史记录未核验', { exact: true })).toBeVisible();
  await settingsCategory(page, '集成');
  const historicalRuntime = page.getByRole('row').filter({ hasText: 'SYNTHETIC · 未连接 Runtime' });
  await expect(historicalRuntime).toHaveCount(1);
  await historicalRuntime.getByRole('button', { name: '配置与原生探测', exact: true }).click();
  await expect(page.getByText('当前共同支持的任务：没有可准入的任务', { exact: true })).toBeVisible();
  await expect(page.getByRole('button', { name: '执行原生探测', exact: true })).toBeDisabled();
  await page.getByRole('tab', { name: '目标交付下游', exact: true }).click();
  await expect(page.getByText('暂无下游服务', { exact: true })).toBeVisible();
  await settingsCategory(page, '迁移');
  await expect(page.getByText('尚无历史导入报告。', { exact: true })).toBeVisible();
  await settingsCategory(page, 'Codex');
  await expect(page.getByRole('button', { name: '登记 Codex 配置', exact: true })).toHaveCount(0);
  await expect(page.getByRole('button', { name: '模型设置', exact: true })).toBeVisible();
  await expect(page.getByText('SYNTHETIC · Demo Researcher', { exact: true }).first()).toBeVisible();
  const denied = await page.request.post('/api/v2/handoffs/arbitrary/claim', { data: {} });
  expect(denied.status()).toBe(403);
  expect((await denied.json()).detail).toContain('不执行');
  expect(failures).toEqual([]);
});
