// Controlled frontend fixtures only; no native business-path claim.
import type { ExitPreview, ExitView } from './capital-exit-state';
export const id = '018fc823-8e40-7000-8000-000000000001';
export const source = '018fc823-8e40-7000-8000-000000000002';
export const intent = '018fc823-8e40-7000-8000-000000000003';
export const amount = { amount: '9007199254740993.123456789', currency: 'USD' };
export const time = '2026-10-07T00:00:00Z'; export const until = '2026-10-08T00:00:00Z';
export const preview: ExitPreview = { schema_version: 1, id, project_id: id, account_source_id: source, original_observation_id: id, environment: 'PAPER', managed_account_key: 'original-managed-account', owner_binding_ref: 'original-owner', expected_account_control_revision: '9007199254740993', scope: { kind: 'AMOUNT', ...amount }, policy: { kind: 'CASH_ONLY' }, plan_artifact_id: id, evidence_refs: [id], valid_until: until, funds: { requested: amount, native_total_cash: null, native_free_cash: null, native_locked_cash: null, verified_idle_cash: null, estimated_release: null, native_equity: null, managed_capital_before: null, remaining_managed_capital: null, estimated_execution_cost: null, existing_unrealized_pnl: null }, proposed_cancellations: [], retained_protective_orders: [], reduction_legs: [], remaining_risk_evidence_id: null, capability: 'SUPPORTED', reason_codes: [] };
export const exit: ExitView = { schema_version: 1, id: intent, project_id: id, account_source_id: source, environment: 'PAPER', managed_account_key: 'original-managed-account', owner_binding_ref: 'original-owner', account_control_epoch: '9007199254740993', account_control_revision: '9007199254740994', revision: '9007199254740993', state: 'PAUSED', last_phase: 'REDUCING', reason_codes: [], preview_id: id, plan_artifact_id: id, scope: preview.scope, policy: preview.policy, command_id: id, owner_command: { schema_version: 1, command_id: id, account_control_epoch: '9007199254740993', instruction: { action: 'PAUSE' } }, external_claim_id: null, remaining_trading: 'FENCED_PENDING_TARGET', funds: { requested_amount: amount, reserved_amount: amount, released_cash_amount: { amount: '10', currency: 'USD' }, verified_withdrawable_amount: { amount: '10', currency: 'USD' }, reconciled_withdrawal_amount: { amount: '0', currency: 'USD' }, unreleased_amount: null, evidence_asof: time, evidence_valid_until: until, withdrawability: 'SIMULATED' }, evidence_refs: [id], created_at: time, updated_at: time };
