[package]
name = "qz-domain"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license-file.workspace = true
repository.workspace = true
publish = false

[dependencies]
qz-contracts = { path = "../qz-contracts" }
chrono = { version = "=0.4.41", features = ["serde"] }
thiserror = "=2.0.16"

[dev-dependencies]
serde_json.workspace = true
proptest = "=1.7.0"
