events {}

http {
    resolver 127.0.0.11 valid=5s ipv6=off;
    access_log off;

    server {
        listen 8011;
        location / {
            set $research_runtime http://research-runtime:8011;
            proxy_pass $research_runtime;
            proxy_http_version 1.1;
            proxy_set_header Connection "";
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }

    server {
        listen 8012;
        location / {
            set $sealed_runtime http://sealed-runtime:8011;
            proxy_pass $sealed_runtime;
            proxy_http_version 1.1;
            proxy_set_header Connection "";
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}
