import { CaretDownIcon, CaretUpDownIcon, CaretUpIcon, MagnifyingGlassIcon } from '@phosphor-icons/react';
import { TextField, Button } from '@radix-ui/themes';
import { flexRender, getCoreRowModel, getFilteredRowModel, getPaginationRowModel, getSortedRowModel, type ColumnDef, type SortingState, useReactTable } from '@tanstack/react-table';
import { useMemo, useState } from 'react';
import { EmptyState } from './EmptyState';

export function DataTable<T>({ data, columns, searchPlaceholder = 'Filter rows…', emptyTitle = 'No records', emptyDescription = 'No data matched the current filters.', initialPageSize = 20, getRowId }: { data: T[]; columns: ColumnDef<T, unknown>[]; searchPlaceholder?: string; emptyTitle?: string; emptyDescription?: string; initialPageSize?: number; getRowId?: (row: T) => string; }) {
  const [sorting, setSorting] = useState<SortingState>([]);
  const [globalFilter, setGlobalFilter] = useState('');
  const stableColumns = useMemo(() => columns, [columns]);
  const table = useReactTable({ data, columns: stableColumns, state: { sorting, globalFilter }, onSortingChange: setSorting, onGlobalFilterChange: setGlobalFilter, getCoreRowModel: getCoreRowModel(), getFilteredRowModel: getFilteredRowModel(), getSortedRowModel: getSortedRowModel(), getPaginationRowModel: getPaginationRowModel(), initialState: { pagination: { pageSize: initialPageSize, pageIndex: 0 } }, getRowId });
  if (data.length === 0) return <EmptyState title={emptyTitle} description={emptyDescription} />;
  return <div className="qz-table-shell"><div className="qz-table-toolbar"><TextField.Root className="qz-table-search" size="1" value={globalFilter} onChange={(event) => setGlobalFilter(event.target.value)} placeholder={searchPlaceholder}><TextField.Slot><MagnifyingGlassIcon size={14} /></TextField.Slot></TextField.Root><span className="qz-section-meta qz-number">{table.getFilteredRowModel().rows.length} rows</span></div><div style={{ overflowX: 'auto' }}><table className="qz-table"><thead>{table.getHeaderGroups().map((group) => <tr key={group.id}>{group.headers.map((header) => <th key={header.id} colSpan={header.colSpan}>{header.isPlaceholder ? null : header.column.getCanSort() ? <button className="qz-sort-button" type="button" onClick={header.column.getToggleSortingHandler()}>{flexRender(header.column.columnDef.header, header.getContext())}{header.column.getIsSorted() === 'asc' ? <CaretUpIcon size={11}/> : header.column.getIsSorted() === 'desc' ? <CaretDownIcon size={11}/> : <CaretUpDownIcon size={11}/>}</button> : flexRender(header.column.columnDef.header, header.getContext())}</th>)}</tr>)}</thead><tbody>{table.getRowModel().rows.map((row) => <tr key={row.id}>{row.getVisibleCells().map((cell) => <td key={cell.id}>{flexRender(cell.column.columnDef.cell, cell.getContext())}</td>)}</tr>)}</tbody></table></div><div className="qz-table-pagination"><span className="qz-number">Page {table.getState().pagination.pageIndex + 1} / {Math.max(1, table.getPageCount())}</span><div style={{ display: 'flex', gap: 6 }}><Button size="1" variant="soft" disabled={!table.getCanPreviousPage()} onClick={() => table.previousPage()}>Previous</Button><Button size="1" variant="soft" disabled={!table.getCanNextPage()} onClick={() => table.nextPage()}>Next</Button></div></div></div>;
}
